Create diagrams
Palingenae/OC-P7-BileMo pull request #4
Opened 2022-04-21 14:57 UTC by Palingenae

Closes #2

2022-04-22 09:12 UTC, soyuka commented on doc/diagrams/sequence_delete-operations.md
> +    U ->> S: Request resource to delete in client in JSON format
> Request resource to delete in client in JSON format

Je comprends pas trop la phrase

2022-04-22 09:12 UTC, soyuka commented on doc/diagrams/sequence_delete-operations.md
> +        else User makes request out of their roles
mauvaise formulation

2022-04-22 09:12 UTC, soyuka commented on doc/diagrams/sequence_delete-operations.md
> +    else User does not have API key
```suggestion
    else User does not have API key or has a bad API key
```

2022-04-22 09:16 UTC, Palingenae commented on doc/diagrams/sequence_delete-operations.md
> +    U ->> S: Request resource to delete in client in JSON format
Quand on veut faire la requête dans genre Postman

2022-04-22 09:24 UTC, Deuchnord requested changes

2022-04-22 09:24 UTC, Deuchnord commented on doc/diagrams/classes.md
> +        class Person {
`Person` pourrait être abstraite, non ?

2022-04-22 09:24 UTC, Deuchnord commented on doc/diagrams/classes.md
> +        Partner "1..n" --> "0..n" Customer: Sells to
Il faut utiliser les liaisons de composition ou d'aggrégation ici
(cf https://github.com/mermaid-js/mermaid/blob/develop/docs/classDiagram.md#defining-relationship)

2022-04-22 09:28 UTC, Palingenae commented on doc/diagrams/classes.md
> +        class Person {
Ho si, j'avais pas vu dans la doc que c'était possible de l'indiquer en vrai ! Merci !

2022-05-10 16:15 UTC, gth076 approved these changes

2022-05-10 16:15 UTC, merged